language: node_js
node_js:
- '12'
sudo: required
services:
- docker
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
  global:
  - OWNER=streamr
  - IMAGE_NAME=smart-contracts-init
  - secure: hMMOm8EB6krNq3fEhSm2pszLualzndHr1PnZE17TdXIZ0vUnP46Ub/Ofz57Da40kuhlNziAuRXV82hhL+3AAXE/gNMCEsTFU5jkwWUB1Gas1ZBGsZnZgv2I/IWn+rfSIDMGzxD38vr+Z/qNno2gCmKxaGTWYqYTvQUtnyjzZO4lWyaaSgqznqtDAlfaq5iq2JgI6ie0DTcS0de+jagbhDzw0tjRjsNEHpj+5ybYPmT16ZYaq4OjF6npx+wfO4udNiV4ggASBcCfN/gVKkyLqdhE1MCbznSld1Rtf0cOmQiOEf1ZDbyuChMzOxkkz+n8I1DBvbt6xNTWF+T/5OnLNaaUK+I6lm+7xD6YEWym0VzmdInXYRKBYBczb2cdQPiy6wBG/9VqYGlRqBqd1JPCDF+8lmS0fZZ/4DuPxj3XmpME71eWO7+LFzE/GFc4dM1aQcK/sIEBc0mrntXJ3EiBba3E37PihS7H//49lvJa8YRy4ScQCtK1ugq+HDdDo5aQ/f1QUm8lJ6l6L8rpKcTvBD4KB5xk2tph8PNlWUVpZdsd7t4/9vlDmi5TECIchDSRHpRTymbHebCa1txGYMsMG0QyPRVnJCKc83PBYzYXGwKe3kv4ZhiBIDvgaFLma6F8TETD8IQGodnZ9HkXye9ueqFOT/Wz42+kxV/NiRp6AOLg=
  - secure: d0cKWNL6L+IPkvCjHxjvxoQFpBdbTjxEobJ8hqEnevQA8rOkkgVBHP6h5aVhegdq1vh8c3ZOtVvHpOKFZn9LrCY4d3/fDbzjrUhoBGmw78RiX/00ukz5ZaM6m8GM9fjXRtAenr3C+9Fhb7jdwxHM13Hr75TYF+Kg+HWbKoVqbBMjd0lK//0tWzLyYbvO8FgI0xVwe4MksZfRgP8FRejAurjuhCtbYEZ714u/JmLpWUS7VhzmzYpKv/mF9LjavljP565ltXBjLC3Afd2taLqVWrVioiEzQFW8SaUH5Gefhu4DAel2gZBoJi4eEvya0MwpXkjB/cBFuT1PP0eSxyoOtel7fKEjeHKgV/wXfqyAEIgcaZ1XEaZpu4zPdoR0zrcS/TGszYqCc08b86+PnP8Zx8Ibc/MFeG4AAipLf6k54aJxoyGm14b1stknNIOpihWJC8mEXILaGjuxrCrUtlR22Sct1HkGiiSKiZgQn1hWyv/IXdzpqmg9FLBKp3HKA0SS17UM4JhmilW98e/mDO55SB7EHM3uHLhAmqgoiJboqtj3AAUE50WvyHwL1Ww6IXhC3a0kueJaHmtPkKeNE55KXrAqGeek8uyakE38zBzlY2QTxmSReNa0JwyeYn5/kdvp9co1d1eejmLOYauUyCqaOt9w3kouuBu1X4yB9UjRuAE=
jobs:
  include:
  - stage: Lint
    script:
    - npm run lint
  - stage: Build docker (Dev/Nightly)
    if: tag IS blank
    install: true
    script:
    - docker build -t $OWNER/$IMAGE_NAME:local .
    deploy:
    - provider: script
      script: ".travis_scripts/deploy_docker.sh dev"
  - stage: Build docker (Production)
    if: tag IS present
    install: true
    script:
    - docker build -t $OWNER/$IMAGE_NAME:local .
    deploy:
    - provider: script
      script: ".travis_scripts/deploy_docker.sh production"
