version: "3"
services:
    parity-sidechain-node0:
         container_name: streamr-dev-parity-sidechain-node0
         environment:
            CHAIN_ID: 0x2325
         image: streamr/open-ethereum-poa:dev
         ports:
           - "8546:8540"
           - "8451:8450"
           - "30310:30309"
         restart: on-failure
         healthcheck:
            test: ["CMD", "curl", "-sS", "http://localhost:8540"]
            interval: 1m30s
            timeout: 10s
            retries: 3
         command: --chain ./streamr-spec.json --config ./node0.toml
    smart-contracts-init:
         container_name: streamr-dev-smart-contracts-init
         image: streamr/smart-contracts-init:dev
         depends_on:
           - parity-sidechain-node0
         environment:
            SIDECHAIN_URL: http://10.200.10.1:8546
            DEBUG: '*'
         volumes:
           - /var/run/docker.sock:/var/run/docker.sock
