name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*

jobs:
  test:
    name: Run tests
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - node_version: 14
            os: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Node ${{ matrix.node_version }} - x64 on ${{ matrix.os }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node_version }}
      - uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build and lint
        run: npm run build && npm run lint
      - name: Unit tests
        run: npm run test
      # TODO: later we might want to run integration tests
      # - name: Start Streamr Docker Stack
      #   uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.3
      #   with:
      #     services-to-start: 'parity-sidechain-node0 parity-node0 bridge'
      # - name: Integration Test
      #   env:
      #     DEBUG: '*'
      #     TEST_TIMEOUT: '600000'
      #   run: npm run integration-test
