# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '08:00'
      timezone: Europe/Helsinki
    open-pull-requests-limit: 5
    labels:
      - ci
    assignees:
      - samt1803
      - jtakalai
      - kare

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '08:00'
      timezone: Europe/Helsinki
    open-pull-requests-limit: 5
    labels:
      - build
    assignees:
      - samt1803
      - jtakalai
      - kare

