#
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#docker
#
---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '08:00'
      timezone: Europe/Helsinki
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    labels:
      - ci
    assignees:
      - DaisyDomergue

  - package-ecosystem: npm
    directory: /packages/config
    schedule:
      interval: daily
      time: '08:00'
      timezone: Europe/Helsinki
    open-pull-requests-limit: 2
    commit-message:
      prefix: build
      include: scope
    labels:
      - build

  - package-ecosystem: npm
    directory: /packages/network-contracts
    schedule:
      interval: daily
      time: '08:00'
      timezone: Europe/Helsinki
    open-pull-requests-limit: 2
    commit-message:
      prefix: build
      include: scope
    labels:
      - build

  - package-ecosystem: npm
    directory: /packages/network-subgraphs
    schedule:
      interval: daily
      time: '08:00'
      timezone: Europe/Helsinki
    open-pull-requests-limit: 2
    commit-message:
      prefix: build
      include: scope
    labels:
      - build

  - package-ecosystem: docker
    directory: /packages/network-subgraphs
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Helsinki
    open-pull-requests-limit: 5
    commit-message:
      prefix: build(docker)
    labels:
      - build

  - package-ecosystem: docker
    directory: ./packages/dev-chain-fast
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Helsinki
    open-pull-requests-limit: 5
    commit-message:
      prefix: build(docker)
    labels:
      - build
