name: Integration tests

on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  unit-test:
    name: Build & Test
    timeout-minutes: 20
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Run build
        run: npm run build
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm run test

  # integration-test:
  #   name: Integration tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 14

  #     - name: Setup dependencies
  #       run: npm ci

  #     - name: Lint
  #       run: npm run lint

  #     - name: Setup streamr-docker-dev environment
  #       run: |
  #         sudo service mysql stop
  #         git clone https://github.com/streamr-dev/streamr-docker-dev.git
  #         sudo ifconfig docker0 10.200.10.1/24
  #         ${GITHUB_WORKSPACE}/streamr-docker-dev/streamr-docker-dev/bin.sh start --wait

  #     - name: Run integration tests
  #       run: npm run test
  #       env:
  #         DEBUG: Streamr*
