/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IJoinPolicy, IJoinPolicyInterface } from "../IJoinPolicy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "broker",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "checkAbleToJoin",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "param",
        type: "uint256",
      },
    ],
    name: "setParam",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IJoinPolicy__factory {
  static readonly abi = _abi;
  static createInterface(): IJoinPolicyInterface {
    return new utils.Interface(_abi) as IJoinPolicyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJoinPolicy {
    return new Contract(address, _abi, signerOrProvider) as IJoinPolicy;
  }
}
