/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  WeightStrategy,
  WeightStrategyInterface,
} from "../WeightStrategy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "nodeAddress",
        type: "address",
      },
    ],
    name: "getWeight",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class WeightStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): WeightStrategyInterface {
    return new utils.Interface(_abi) as WeightStrategyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): WeightStrategy {
    return new Contract(address, _abi, signerOrProvider) as WeightStrategy;
  }
}
