/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface BountyInterface extends utils.Interface {
  contractName: "Bounty";
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "a()": FunctionFragment;
    "allocationWeiPerSecond()": FunctionFragment;
    "brokers(uint256)": FunctionFragment;
    "cueAtJoinWei(address)": FunctionFragment;
    "cueTimestamp()": FunctionFragment;
    "cumulativeUnitEarningsWei()": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getState()": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "horizonSeconds()": FunctionFragment;
    "initialize(address,uint256,uint256,uint256,uint256,uint256,address,address,address,address)": FunctionFragment;
    "isTrustedForwarder(address)": FunctionFragment;
    "join(address)": FunctionFragment;
    "leave(address)": FunctionFragment;
    "maxBrokerCount()": FunctionFragment;
    "minBrokerCount()": FunctionFragment;
    "minHorizonSeconds()": FunctionFragment;
    "minimumStakeWei()": FunctionFragment;
    "onTokenTransfer(address,uint256,bytes)": FunctionFragment;
    "refresh()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "sponsor(uint256)": FunctionFragment;
    "stake(address,uint256)": FunctionFragment;
    "stakedWei(address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "token()": FunctionFragment;
    "totalSponsorshipsAtCueTimestamp()": FunctionFragment;
    "totalStakeWei()": FunctionFragment;
    "unallocatedWei()": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
    "withdrawableEarnings(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "a", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allocationWeiPerSecond",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "brokers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cueAtJoinWei",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "cueTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cumulativeUnitEarningsWei",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getState", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "horizonSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "join", values: [string]): string;
  encodeFunctionData(functionFragment: "leave", values: [string]): string;
  encodeFunctionData(
    functionFragment: "maxBrokerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minBrokerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minHorizonSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumStakeWei",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onTokenTransfer",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "refresh", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sponsor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stakedWei", values: [string]): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSponsorshipsAtCueTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStakeWei",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unallocatedWei",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawableEarnings",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "a", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allocationWeiPerSecond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "brokers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cueAtJoinWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cueTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cumulativeUnitEarningsWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getState", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "horizonSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "join", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "leave", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxBrokerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minBrokerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minHorizonSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumStakeWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onTokenTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refresh", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sponsor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakedWei", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSponsorshipsAtCueTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStakeWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unallocatedWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawableEarnings",
    data: BytesLike
  ): Result;

  events: {
    "BrokerJoined(address)": EventFragment;
    "BrokerLeft(address,uint256)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "SponsorshipReceived(address,uint256)": EventFragment;
    "StakeAdded(address,uint256,uint256)": EventFragment;
    "StateChanged(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BrokerJoined"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BrokerLeft"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SponsorshipReceived"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StateChanged"): EventFragment;
}

export type BrokerJoinedEvent = TypedEvent<[string], { broker: string }>;

export type BrokerJoinedEventFilter = TypedEventFilter<BrokerJoinedEvent>;

export type BrokerLeftEvent = TypedEvent<
  [string, BigNumber],
  { broker: string; returnedStakeWei: BigNumber }
>;

export type BrokerLeftEventFilter = TypedEventFilter<BrokerLeftEvent>;

export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  { role: string; previousAdminRole: string; newAdminRole: string }
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  { role: string; account: string; sender: string }
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  { role: string; account: string; sender: string }
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export type SponsorshipReceivedEvent = TypedEvent<
  [string, BigNumber],
  { sponsor: string; amount: BigNumber }
>;

export type SponsorshipReceivedEventFilter =
  TypedEventFilter<SponsorshipReceivedEvent>;

export type StakeAddedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { broker: string; addedWei: BigNumber; totalWei: BigNumber }
>;

export type StakeAddedEventFilter = TypedEventFilter<StakeAddedEvent>;

export type StateChangedEvent = TypedEvent<[number], { newState: number }>;

export type StateChangedEventFilter = TypedEventFilter<StateChangedEvent>;

export interface Bounty extends BaseContract {
  contractName: "Bounty";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BountyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    a(overrides?: CallOverrides): Promise<[BigNumber]>;

    allocationWeiPerSecond(overrides?: CallOverrides): Promise<[BigNumber]>;

    brokers(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    cueAtJoinWei(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    cueTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    cumulativeUnitEarningsWei(overrides?: CallOverrides): Promise<[BigNumber]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getState(overrides?: CallOverrides): Promise<[number]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    horizonSeconds(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      tokenAddress: string,
      initialAllocationWeiPerSecond: BigNumberish,
      initialMinBrokerCount: BigNumberish,
      initialMaxBrokerCount: BigNumberish,
      initialMinimumStakeWei: BigNumberish,
      initialMinHorizonSeconds: BigNumberish,
      _joinPolicy: string,
      _leavePolicy: string,
      _allocationPolicy: string,
      trustedForwarderAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    join(
      broker: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    leave(
      broker: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    maxBrokerCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    minBrokerCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    minHorizonSeconds(overrides?: CallOverrides): Promise<[BigNumber]>;

    minimumStakeWei(overrides?: CallOverrides): Promise<[BigNumber]>;

    onTokenTransfer(
      arg0: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    refresh(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sponsor(
      amountTokenWei: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stake(
      broker: string,
      amountTokenWei: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakedWei(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    token(overrides?: CallOverrides): Promise<[string]>;

    totalSponsorshipsAtCueTimestamp(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalStakeWei(overrides?: CallOverrides): Promise<[BigNumber]>;

    unallocatedWei(overrides?: CallOverrides): Promise<[BigNumber]>;

    withdraw(
      amountTokenWei: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawableEarnings(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  a(overrides?: CallOverrides): Promise<BigNumber>;

  allocationWeiPerSecond(overrides?: CallOverrides): Promise<BigNumber>;

  brokers(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  cueAtJoinWei(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  cueTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  cumulativeUnitEarningsWei(overrides?: CallOverrides): Promise<BigNumber>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  getState(overrides?: CallOverrides): Promise<number>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  horizonSeconds(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    tokenAddress: string,
    initialAllocationWeiPerSecond: BigNumberish,
    initialMinBrokerCount: BigNumberish,
    initialMaxBrokerCount: BigNumberish,
    initialMinimumStakeWei: BigNumberish,
    initialMinHorizonSeconds: BigNumberish,
    _joinPolicy: string,
    _leavePolicy: string,
    _allocationPolicy: string,
    trustedForwarderAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isTrustedForwarder(
    forwarder: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  join(
    broker: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  leave(
    broker: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  maxBrokerCount(overrides?: CallOverrides): Promise<BigNumber>;

  minBrokerCount(overrides?: CallOverrides): Promise<BigNumber>;

  minHorizonSeconds(overrides?: CallOverrides): Promise<BigNumber>;

  minimumStakeWei(overrides?: CallOverrides): Promise<BigNumber>;

  onTokenTransfer(
    arg0: string,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  refresh(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sponsor(
    amountTokenWei: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stake(
    broker: string,
    amountTokenWei: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakedWei(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  token(overrides?: CallOverrides): Promise<string>;

  totalSponsorshipsAtCueTimestamp(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  totalStakeWei(overrides?: CallOverrides): Promise<BigNumber>;

  unallocatedWei(overrides?: CallOverrides): Promise<BigNumber>;

  withdraw(
    amountTokenWei: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawableEarnings(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    a(overrides?: CallOverrides): Promise<BigNumber>;

    allocationWeiPerSecond(overrides?: CallOverrides): Promise<BigNumber>;

    brokers(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    cueAtJoinWei(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    cueTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    cumulativeUnitEarningsWei(overrides?: CallOverrides): Promise<BigNumber>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    getState(overrides?: CallOverrides): Promise<number>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    horizonSeconds(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      tokenAddress: string,
      initialAllocationWeiPerSecond: BigNumberish,
      initialMinBrokerCount: BigNumberish,
      initialMaxBrokerCount: BigNumberish,
      initialMinimumStakeWei: BigNumberish,
      initialMinHorizonSeconds: BigNumberish,
      _joinPolicy: string,
      _leavePolicy: string,
      _allocationPolicy: string,
      trustedForwarderAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    join(broker: string, overrides?: CallOverrides): Promise<void>;

    leave(broker: string, overrides?: CallOverrides): Promise<void>;

    maxBrokerCount(overrides?: CallOverrides): Promise<BigNumber>;

    minBrokerCount(overrides?: CallOverrides): Promise<BigNumber>;

    minHorizonSeconds(overrides?: CallOverrides): Promise<BigNumber>;

    minimumStakeWei(overrides?: CallOverrides): Promise<BigNumber>;

    onTokenTransfer(
      arg0: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    refresh(overrides?: CallOverrides): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    sponsor(
      amountTokenWei: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stake(
      broker: string,
      amountTokenWei: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stakedWei(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    token(overrides?: CallOverrides): Promise<string>;

    totalSponsorshipsAtCueTimestamp(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalStakeWei(overrides?: CallOverrides): Promise<BigNumber>;

    unallocatedWei(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      amountTokenWei: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawableEarnings(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "BrokerJoined(address)"(broker?: string | null): BrokerJoinedEventFilter;
    BrokerJoined(broker?: string | null): BrokerJoinedEventFilter;

    "BrokerLeft(address,uint256)"(
      broker?: string | null,
      returnedStakeWei?: null
    ): BrokerLeftEventFilter;
    BrokerLeft(
      broker?: string | null,
      returnedStakeWei?: null
    ): BrokerLeftEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;

    "SponsorshipReceived(address,uint256)"(
      sponsor?: string | null,
      amount?: null
    ): SponsorshipReceivedEventFilter;
    SponsorshipReceived(
      sponsor?: string | null,
      amount?: null
    ): SponsorshipReceivedEventFilter;

    "StakeAdded(address,uint256,uint256)"(
      broker?: string | null,
      addedWei?: null,
      totalWei?: null
    ): StakeAddedEventFilter;
    StakeAdded(
      broker?: string | null,
      addedWei?: null,
      totalWei?: null
    ): StakeAddedEventFilter;

    "StateChanged(uint8)"(newState?: null): StateChangedEventFilter;
    StateChanged(newState?: null): StateChangedEventFilter;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    a(overrides?: CallOverrides): Promise<BigNumber>;

    allocationWeiPerSecond(overrides?: CallOverrides): Promise<BigNumber>;

    brokers(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    cueAtJoinWei(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    cueTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    cumulativeUnitEarningsWei(overrides?: CallOverrides): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getState(overrides?: CallOverrides): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    horizonSeconds(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      tokenAddress: string,
      initialAllocationWeiPerSecond: BigNumberish,
      initialMinBrokerCount: BigNumberish,
      initialMaxBrokerCount: BigNumberish,
      initialMinimumStakeWei: BigNumberish,
      initialMinHorizonSeconds: BigNumberish,
      _joinPolicy: string,
      _leavePolicy: string,
      _allocationPolicy: string,
      trustedForwarderAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    join(
      broker: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    leave(
      broker: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    maxBrokerCount(overrides?: CallOverrides): Promise<BigNumber>;

    minBrokerCount(overrides?: CallOverrides): Promise<BigNumber>;

    minHorizonSeconds(overrides?: CallOverrides): Promise<BigNumber>;

    minimumStakeWei(overrides?: CallOverrides): Promise<BigNumber>;

    onTokenTransfer(
      arg0: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    refresh(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sponsor(
      amountTokenWei: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stake(
      broker: string,
      amountTokenWei: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakedWei(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    totalSponsorshipsAtCueTimestamp(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalStakeWei(overrides?: CallOverrides): Promise<BigNumber>;

    unallocatedWei(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      amountTokenWei: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawableEarnings(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    a(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allocationWeiPerSecond(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    brokers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cueAtJoinWei(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cueTimestamp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cumulativeUnitEarningsWei(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    horizonSeconds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      tokenAddress: string,
      initialAllocationWeiPerSecond: BigNumberish,
      initialMinBrokerCount: BigNumberish,
      initialMaxBrokerCount: BigNumberish,
      initialMinimumStakeWei: BigNumberish,
      initialMinHorizonSeconds: BigNumberish,
      _joinPolicy: string,
      _leavePolicy: string,
      _allocationPolicy: string,
      trustedForwarderAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    join(
      broker: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    leave(
      broker: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    maxBrokerCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minBrokerCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minHorizonSeconds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minimumStakeWei(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onTokenTransfer(
      arg0: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    refresh(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sponsor(
      amountTokenWei: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stake(
      broker: string,
      amountTokenWei: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakedWei(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSponsorshipsAtCueTimestamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalStakeWei(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unallocatedWei(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      amountTokenWei: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawableEarnings(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
