/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { TokenGateDeployer } from "../TokenGateDeployer";

export class TokenGateDeployer__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenGateDeployer {
    return new Contract(address, _abi, signerOrProvider) as TokenGateDeployer;
  }
}

const _abi = [
  {
    inputs: [],
    name: "delegatedAccessRegistryAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "streamId_",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "minRequiredBalance_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "stakingEnabled_",
        type: "bool",
      },
      {
        internalType: "enum StreamRegistryV3.PermissionType[]",
        name: "defaultPermissions_",
        type: "uint8[]",
      },
    ],
    name: "deploy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "registry",
    outputs: [
      {
        internalType: "contract JoinPolicyRegistry",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "streamRegistry",
    outputs: [
      {
        internalType: "contract StreamRegistryV3",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "streamRegistryAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
