---
name: Continuous Integration

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  integration-tests:
    needs:
      - lint-and-unit-test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules
            packages/*/node_modules
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm ci --no-audit
          npm i @nomicfoundation/solidity-analyzer-linux-x64-gnu
      - name: Build packages
        run: npm run build -w packages/network-contracts -w packages/config
      - name: Start Streamr Docker Stack
        uses: streamr-dev/streamr-docker-dev-action@v1.0.1
        with:
          services-to-start: 'ens-sync-script deploy-network-subgraphs'
      - name: Integration Test (with dev-docker environment)
        env:
          TEST_TIMEOUT: '600000'
          DEBUG: "*,-mocha:*"
        run: npm run integration-test
