---
name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*

jobs:
  test:
    name: Run tests
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - node_version: 16
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install Node 
        uses: actions/setup-node@v2.5.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: |
            ./package-lock.json
            ./packages/smartcontracts/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build and lint
        run: npm run build && npm run lint
      - name: Unit tests
        run: npm run test
