---
name: streamr-config package
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: config-ci-${{ github.head_ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: |
            ./package-lock.json
      - run: |
          npm ci
          cd packages/config
          npm run lint
          npm run test
          npm run build
